#----------------------------------------------------------------------------#
#                                                                            #
#    ejecute el comando make help para ver los objetivos disponibles         #
#                                                                            #
#----------------------------------------------------------------------------#

PROGSUSR =  \
# programas de usuario "normales":
# --------------------------------
  prog_0/   \
            \
# drivers:
# -------
# consola/  \
# conrat/   \
# raton/    \
# reloj/    \
# retardo/  \
# timer/
  
DIRS          = $(PROGSUSR:/=)
DIRS.clean    = $(PROGSUSR:/=.clean)
DIRS.pule     = $(PROGSUSR:/=.pule)
DIRS.disquete = $(PROGSUSR:/=.disquete) 
  
do: $(DIRS:prog_0=)
  cd prog_0
  $(MAKE)
  @cd ..

$(DIRS:help=):
  cd $*
  $(MAKE)
  cd ..  
    
build: clean do 

clean: $(DIRS.clean)

$(DIRS.clean):
  cd $*
  @"$(MAKE) clean" | extraer +l 1
  @cd ..

pule: $(DIRS.pule)

$(DIRS.pule):
  cd $*
  @"$(MAKE) pule" | extraer +l 1
  @cd ..

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make            genera el .BIN de cada uno de los programas de usuario"
  @"echo    make pule       borra todo salvo los .BIN, fuentes y MAKEFILEs"
  @"echo    make clean      borra todo salvo los fuentes y MAKEFILEs"
  @"echo    make help       muestra esta ayuda sobre los objetivos disponibles"



  
!if (0) 

all:
  @echo.
  cd so1hpub
  @make
  @cd ..
  @echo.
  cd so1h
  @make
  @cd ..
  @echo.
  cd progusr
  @make
  @cd ..

clean:
  @echo.
  cd so1hpub
  @make clean > nul
  @cd ..
  cd so1h
  @make clean > nul
  @cd ..
  cd progusr
  @make clean > nul
  @cd ..

build: clean all

run:
  @echo.
  cd so1h
  make run
  @cd ..

runmsdos:
  @echo.
  cd so1h
  make runmsdos
  @cd ..

rundebug:
  @echo.
  cd so1h
  make rundebug
  @cd ..

rundosbox:
  @echo.
  cd so1h
  make rundosbox
  @cd ..

imagen:
  @echo.
  cd so1h
  make imagen
  @cd ..

start:
  @echo.
  cd so1h
  make start
  @cd ..

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make          genera el fichero $(PROGRAMA).bs"
  @"echo    make pule     borra todo salvo $(PROGRAMA).C, MAKEFILE y $(PROGRAMA).bs"
  @"echo    make clean    borra todo salvo $(PROGRAMA).C y MAKEFILE"
  @"echo    make build    borra todo y genera un nuevo fichero $(PROGRAMA).bs"
  @"echo    make imagen   genera una imagen de disquete fd$(PROGRAMA).img
  @"echo    make start    arranca la imagen de disquete fd$(PROGRAMA).img con qemu
  @"echo    make help     muestra esta ayuda sobre los objetivos disponibles"

!endif  
  
!if (0)

PROGSUSR =   \
# programas de usuario "normales":
# --------------------------------
  atexit/   \
  ayuda/    \
  c2c/      \
  clock/    \
  date/     \
  dfs/      \
  dmp/      \
  dp/       \
  dr/       \
  ecodf0_1/ \
  exec/     \
  fork/     \
  hello/    \
  hello2/   \
  help/     \
  inic/     \
  info/     \
  kill/     \
  leetimer/ \
  login/    \
  meapila/  \
  mem/      \
  mouse/    \
  ps/       \
  sh/       \
  testsegs/ \
  time/     \
  ver_args/ \
            \
# drivers:
# -------
  consola/  \
  conrat/   \
  raton/    \
  reloj/    \
  retardo/  \
  timer/

DIRS          = $(PROGSUSR:/=)
DIRS.clean    = $(PROGSUSR:/=.clean)
DIRS.pule     = $(PROGSUSR:/=.pule)
DIRS.disquete = $(PROGSUSR:/=.disquete)
DIRS.show     = $(PROGSUSR:/=.show)
DIRS.hide     = $(PROGSUSR:/=.hide)
DIRS.delsrc   = $(PROGSUSR:/=.delsrc)

do: $(DIRS:help=)
  cd help
  $(MAKE)
  cd ..

$(DIRS:help=):
  cd $*
  $(MAKE)
  cd ..

build: clean disquete

disquete: $(DIRS.disquete)

$(DIRS.disquete):
  cd $*
  @"$(MAKE) disquete" | extraer +l 1
  @cd ..

clean: $(DIRS.clean)

$(DIRS.clean):
  cd $*
  @"$(MAKE) clean" | extraer +l 1
  @cd ..

pule: $(DIRS.pule)

$(DIRS.pule):
  cd $*
  @"$(MAKE) pule" | extraer +l 1
  @cd ..

show: $(DIRS.show)

$(DIRS.show):
  cd $*
  @"$(MAKE) show" | extraer +l 1
  @cd ..

hide: $(DIRS.hide)

$(DIRS.hide):
  cd $*
  @"$(MAKE) hide" | extraer +l 1
  @cd ..

delsrc: $(DIRS.delsrc)

$(DIRS.delsrc):
  cd $*
  @"$(MAKE) delsrc" | extraer +l 1
  @cd ..

run:
  cd ..\disquete
  start so1.exe
# so1.exe

rundosbox:
  cd ..\disquete
  start $(UUSB):\Interno\dosbox-0.74\dosbox.exe so1.exe -noconsole -exit
  exit

rundosboxdbg:
  @echo.
  cd ..\disquete
  start $(UUSB):\Interno\dosbox-0.74\dosbox-74-debug.exe so1.exe -noconsole -exit
  exit



DIRS.otrocomando = $(PROGSUSR:/=.otrocomando)

otrocomando: $(DIRS.otrocomando)

$(DIRS.otrocomando):
  cd $*
# mkdir SOURCE
# copy *.C SOURCE
# if exist $*.C (move $*.C $*.COLD)
  if exist $*.COLD (erase $*.COLD)
# copy *.obj ..\_OCULTOS
  @cd ..

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make            genera el .BIN de cada uno de los programas de usuario"
  @"echo    make pule       borra todo salvo los .BIN, fuentes y MAKEFILEs"
  @"echo    make clean      borra todo salvo los fuentes y MAKEFILEs"
  @"echo    make build      borra todo y genera nuevos ficheros .bin"
  @"echo    make run        ejecuta SO1.EXE en el directorio DISQUETE (Windows)"
  @"echo    make rundosbox  ejecuta SO1.EXE en el directorio DISQUETE (DOSBox)"
  @"echo    make show       mueve los ficheros .C de los directorios SOURCE"
  @"echo    make hide       mueve los ficheros .C a los directorios SOURCE"
  @"echo                    y guarda los .OBJ en los directorios _OCULTOS"
  @"echo    make help       muestra esta ayuda sobre los objetivos disponibles"

!endif