/*
  Copyright (c) 2017, Pedro Pablo Lopez Rodriguez & Julio Lozano Del Pozo
  2-clause BSD license.
*/

/* ----------------------------------------------------------------------- */
/*                                  gm_x.h                                 */
/* ----------------------------------------------------------------------- */
/*   Gestor de Memoria: Particiones variables (Lista de bloques libres)    */
/* ----------------------------------------------------------------------- */

#ifndef GM_X_H
#define GM_X_H

void inicGM_x ( void ) ;

#endif /* GM_X_H */

