/*
  Copyright (c) 2017, Pedro Pablo Lopez Rodriguez & Julio Lozano Del Pozo
  2-clause BSD license.
*/

/* ----------------------------------------------------------------------- */
/*                                procs_x.h                                */
/* ----------------------------------------------------------------------- */
/*                      Gestion de procesos y threads                      */
/* ----------------------------------------------------------------------- */

#ifndef PROCS_X_H
#define PROCS_X_H

#include <so1hpub.h\def_proc.h> /* descSO1H_t, camposDescSO1H, dirDescSO1H */

/* campos de descSO1H declarados como variables: NO MODIFICAR */

camposDescSO1H(extern) 

/* fin campos de descSO1H declarados como variables */

void inicProcesos_x ( void ) ;

#endif