/* ----------------------------------------------------------------------- */
/*                               caracter.h                                */
/* ----------------------------------------------------------------------- */
/*                                                                         */
/* ----------------------------------------------------------------------- */

#ifndef CARACTER_H
#define CARACTER_H

extern char dig[17] ;

/* utilizar toupper y tolower (biblioteca estandar ctype.h */

//char mayuscula ( char letra ) ;

//char minuscula ( char letra ) ;

#endif /* CARACTER_H */

