/* ----------------------------------------------------------------------- */
/*                                  const.h                                */
/* ----------------------------------------------------------------------- */
/*                     principales constantes del sistema                  */
/* ----------------------------------------------------------------------- */

#ifndef CONST_H
#define CONST_H

#define maxProcesos 16                        /* numero maximo de procesos */

#define maxThreads 2010                       /* numero maximo de threads */

#define dfMax 10   /* numero maximo de descriptores de fichero del proceso */

#define dfsMax 20  /* numero maximo de descriptores de fichero del sistema */

#define maxRecursos 14                        /* numero maximo de recursos */

//#define nVIntMax 128                                              /* 256 */
#define nVIntMax 256                                                /* 256 */

#define tamComando 80    /* numero maximo de caracteres en un comando (+1) */

#endif /* CONST_H */

