#----------------------------------------------------------------------------#
#                                                                            #
#    ejecute el comando make help para ver los objetivos disponibles         #
#                                                                            #
#----------------------------------------------------------------------------#

!include "..\MKFILE0"

OBJS = tipos.o caracter.o printgen.o biosdata.o bios_0.o pantalla.o \
       puertos.o cmos.o telon.o colores.o \
	   msdos.o \
	   c2c.o

all: $(OBJS)

.c.o:
!if (0)
  @if not exist asm mkdir asm
  $(CC) $(CFLAGS) -S $&.c -o asm\$&.s
!endif  
  $(CC) $(CFLAGS) -c $&.c

build: clean all

clean:
  @if exist *.o erase *.o
  @if exist asm\*.s erase asm\*.s

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make          genera los ficheros objeto modificados"
  @"echo    make clean    borra todo salvo los fuentes"
  @"echo    make build    borra todo y genera de nuevo los ficheros objeto"

