#----------------------------------------------------------------------------#
#                                                                            #
#    ejecute el comando make help para ver los objetivos disponibles         #
#                                                                            #
#----------------------------------------------------------------------------#

!include "..\MKFILE0"

OBJS = tipos.o caracter.o printgen.o biosdata.o bios_0.o pantalla.o \
       puertos.o cmos.o telon.o colores.o msdos.o c2c.o debug.o \
       pic.o bios_crt.o memvideo.o printvid.o ptrc2c.o ccb.o \
       seccion.o ajustusr.o ll_s_thr.o main.o

.path.o   = .\obj
.path.asm = .\asm
.path.c   = .

all: crearDirs $(OBJS)

!if ($(VIA_ASM) == TRUE)

.c.asm:
  $(CC) $(CFLAGS) -SI $(UUSB):\SO1H\PRACT0 -S $&.c -o asm\$&.asm

.asm.o:
# $(CC) $(CFLAGS) -c asm\$&.asm -o obj\$&.o
  $(AS) -f elf -o obj\$&.o -l lst\$&.lst asm\$&.asm

!else

.c.o:
  $(CC) $(CFLAGS) -SI $(UUSB):\SO1H\PRACT0 -c $&.c -o obj\$&.o

!endif

LISTADIRS = obj.dir asm.dir lst.dir

crearDirs: $(LISTADIRS)

$(LISTADIRS):
  @if not exist $* mkdir $*

build: clean all

clean:
  @if exist obj\*.o erase obj\*.o
  @if exist asm\*.asm erase asm\*.asm
  @if exist lst\*.lst erase lst\*.lst

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make          genera los ficheros objeto modificados"
  @"echo    make clean    borra todo salvo los fuentes"
  @"echo    make build    borra todo y genera de nuevo los ficheros objeto"

