/* ----------------------------------------------------------------------- */
/*                                 dokill.h                                */
/* ----------------------------------------------------------------------- */
/*    codigo comun de la llamadas kill y de cerrar ventana con el raton    */
/* ----------------------------------------------------------------------- */

#ifndef DOKILL_H
#define DOKILL_H

#include "..\so1hpub.h\tipos.h"                                 /* pindx_t */

void doKill ( pindx_t pindx ) ;                /* el proceso pindx termina */

#endif /* DOKILL */