#----------------------------------------------------------------------------#
#                                                                            #
#    ejecute el comando make help para ver los objetivos disponibles         #
#                                                                            #
#----------------------------------------------------------------------------#

DIRS = so1hpub/ \
       so1h/ \
	   so1h_k/ \
       progusr/ \
       so1h_0/

DIRS.cd = $(DIRS:/=.cd)
	   	   
all: $(DIRS.cd) 

$(DIRS.cd):
  @echo.
  cd $&
  @make
  @cd ..

crearDir: 
  @if not exist DISQUETE mkdir DISQUETE  
  
clean: crearDir
  @echo.
  cd so1hpub
  @make clean > nul
  @cd ..
  cd so1h
  @make clean > nul
  @cd ..
  cd so1h_k
  @make clean > nul
  @cd ..
  cd progusr
  @make clean > nul
  @cd ..
  cd so1h_0
  @make clean > nul
  @cd ..
  cd disquete
  @if exist *.bin erase *.bin
  @if exist *.exe erase *.exe
  @if exist stderr.txt erase stderr.txt
  @if exist stdout.txt erase stdout.txt
  @cd ..

build: clean all

run runmsdos rundebug rundosbox imagen start:
  @echo.
  cd so1h
  make $&
  @cd ..
  
help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make          genera el fichero $(PROGRAMA).bs"
  @"echo    make pule     borra todo salvo $(PROGRAMA).C, MAKEFILE y $(PROGRAMA).bs"
  @"echo    make clean    borra todo salvo $(PROGRAMA).C y MAKEFILE"
  @"echo    make build    borra todo y genera un nuevo fichero $(PROGRAMA).bs"
  @"echo    make imagen   genera una imagen de disquete fd$(PROGRAMA).img
  @"echo    make start    arranca la imagen de disquete fd$(PROGRAMA).img con qemu
  @"echo    make help     muestra esta ayuda sobre los objetivos disponibles"


